### ISSUE TITLE
(Seeming non-deterministic) Travis-CI Build Failures

### ISSUE THREAD

**Issue by qayshp** [nmklotas/GitLabApiClient#10]
Looking at https://travis-ci.org/nmklotas/GitLabApiClient/pull_requests

I thought my change in https://github.com/nmklotas/GitLabApiClient/pull/9 would address this, but was wrong. Even though it had built successfully multiple times, it again started to fail with 401 and other errors that lead me to believe the GitLab service was not setup properly for the test run.

Will continue discussion here.

**Comment by qayshp** [comment]
From a daily scheduled travis run on my fork, the same exact commit has passed and failed 4 times each.

![image](https://user-images.githubusercontent.com/714080/39607726-729121b0-4ef1-11e8-877e-a79327e16c6a.png)

In all cases it looks like gitlab wasn't set up correctly, or hadn't started completely.
https://travis-ci.org/qayshp/GitLabApiClient/builds/373378356 was 401s
https://travis-ci.org/qayshp/GitLabApiClient/builds/372929040 was 502s
https://travis-ci.org/qayshp/GitLabApiClient/builds/372622850 was 502s
https://travis-ci.org/qayshp/GitLabApiClient/builds/372346679 was 502s

**Comment by casz** [comment]
We now use fluent docker, that has a option to wait for healthy, using the docker health check 👍
