### ISSUE TITLE
Get list MR?

### ISSUE THREAD

**Issue by TemoxaGreenMoney** [nmklotas/GitLabApiClient#102]
Hi

How i can get merge requests list filter by field "merge_status" ?

And i not found in GetAsync method field "title", "description"?

**Comment by casz** [comment]
To answer your first question:

```csharp
var gitLabClient = new GitLabClient("", "");
var mergeRequests = await gitLabClient.MergeRequests.GetAsync(options =>
  {
    options.State = QueryMergeRequestState.Merged;
  }
);
```

Not sure about second question as both title and description should be on the return object.

**Comment by TemoxaGreenMoney** [comment]
This field not for my task(

I must have MR in status "merge_status=cannot_be_merged"

**Comment by casz** [comment]
@TemoxaGreenMoney this is not something offered in the gitlab api.

You will have to filter by open MRs and filter them using the attribute `has_conflicts`

**Comment by casz** [comment]
Could be that the csharp object does not have all the newer attributes. Feel free to contribute :)

**Comment by TemoxaGreenMoney** [comment]
I solved problem this code

` 
var listMr = await client.MergeRequests.GetAsync();
var listMr = listMr.Where(f => f.Status == MergeStatus.CannotBeMerged).ToList();
`

**Comment by casz** [comment]
@TemoxaGreenMoney you properly still want to filter your GetAsync with `QueryMergeRequestState.Open`

**Comment by TemoxaGreenMoney** [comment]
QueryMergeRequestState - not include need value "cannot_be_merged"

**Comment by casz** [comment]
According to the docs: https://docs.gitlab.com/ee/api/merge_requests.html that state is not included
