### ISSUE TITLE
Do you have any plans to support MockHttp or Moq.Contrib.HttpClient

### ISSUE THREAD

**Issue by hhko** [nmklotas/GitLabApiClient#113]
Do you have any plans to support [MockHttp](https://github.com/richardszalay/mockhttp) or [Moq.Contrib.HttpClient](https://github.com/maxkagamine/Moq.Contrib.HttpClient) for unit test?

**Comment by casz** [comment]
Not sure what a mock framework has to do with writing unit tests for your project?

**Comment by hhko** [comment]
I want to test some test-scenarios without any physical dependence such as gitlab.com.

**Comment by casz** [comment]
Look at our test setup it uses a gitlab container.

**Comment by casz** [comment]
Not sure I am interested in adding support, unless you can demonstrate value by adding a pull request with downstream usage.
