### ISSUE TITLE
Accessing All Issues in a project

### ISSUE THREAD

**Issue by pmsudhi** [nmklotas/GitLabApiClient#131]
I am trying to get All issues in a project by Calling `client.Issues.GetAsync(projectID); ` . Obviously it will return all "Opened" issues in that Project. What i was looking for is to get "ALL" Types of Issues (opened,closed etc). I know the overloaded method takes, `Action<ProjectQueryOption>`. I tried different ways, but unable to get it working. Could some one help me in guiding right way to implement it

**Comment by pmsudhi** [comment]
Managed to solve this issue by making following changes to my code. Thanks to the Test project, which gave away the clue. Updating here for documentation purpose
`Task.Run(() => client.Issues.GetAllAsync(ID, null, options: o => o.State=GitLabApiClient.Models.Issues.Responses.IssueState.All));`

**Comment by jetersen** [comment]
You can drop the `Task.Run` as `GetAllAsync` already returns a task.

**Comment by pmsudhi** [comment]
> You can drop the `Task.Run` as `GetAllAsync` already returns a task.

Thanks @jetersen for pointing out that. corrected the comment. Can you please explain the advantage of using Action Delegate here in parameter instead of passing IssuesQueryOptions object directly?
