### ISSUE TITLE
Unable to filter projects when retrieving them

### ISSUE THREAD

**Issue by venu-kuruganti** [nmklotas/GitLabApiClient#139]
I want to filter out the projects I retrieve from Git based on Path, Name or any other criteria.

Currently I'm retrieving projects like so:

`var gitProjects = await gitClient.Projects.GetAsync();`

Is there some parameter I can pass to the **GetAsync** function which will filter out the projects before retrieving them?

I checked the code for Projects.GetAsync() and found that it takes 

`Action<ProjectQueryOptions> options`

as a parameter. But I cannot instantiate a class of ProjectQueryOptions as the constructor is not **public**.

Need help?

**Comment by jetersen** [comment]
You do not construct a ProjectQueryOptions, you pass it as an action:

```csharp
var gitProjects = await gitClient.Projects.GetAsync(o => o.Filter = "hey");
```

**Comment by venu-kuruganti** [comment]
> 
> 
> You do not construct a ProjectQueryOptions, you pass it as an action:
> 
> ```cs
> var gitProjects = await gitClient.Projects.GetAsync(o => o.Filter = "hey");
> ```

OKay but what if I want to include multiple parameters for the filter? How do I separate them out and then pass them in?

**Comment by jetersen** [comment]
Gitlab's search filter is not that advanced.

Your better off fetching all projects and than use Linq to filter your projects.
