### ISSUE TITLE
how to enable ssl connection please?

### ISSUE THREAD

**Issue by benothmencode** [nmklotas/GitLabApiClient#151]
HttpRequestException: The SSL connection could not be established, see inner exception. i have this error , whenever i run my app , i'm using a gitlab server locally for project reasons , i just need to enable ssl connection ...

**Comment by FlYnN91** [comment]
I am getting this when trying to connect to Gitlab Cloud from my web app.

**Comment by benothmencode** [comment]
Hi , i end up changing my gitlab url server to http instead of https , i no
longer have a prob. Hope i helped , have a nice day .

Le ven. 26 juin 2020 à 09:41, Dainius Narsutis <notifications@github.com> a
écrit :

**Comment by nmklotas** [comment]
Looks like this has been sorted out
