### ISSUE TITLE
Error with new MergeStatus entry

### ISSUE THREAD

**Issue by Redblueflame** [nmklotas/GitLabApiClient#157]
It seems like that Gitlab has added a new merge request status, breaking every single search for a Merge Request.
I have this error:
```
Error converting value "cannot_be_merged_recheck" to type 'GitLabApiClient.Models.MergeRequests.Responses.MergeStatus'. Path '[1].merge_status', line 1, position 2244
```

**Comment by TemoxaGreenMoney** [comment]
I have this problem too :(

**Comment by TemoxaGreenMoney** [comment]
@nmklotas  @jetersen fyi pls

**Comment by TemoxaGreenMoney** [comment]
How long wait answer? Maybe anybody know better library for GitLab Api ?

**Comment by jetersen** [comment]
Your free to contribute to the project.

**Comment by TemoxaGreenMoney** [comment]
Yes, but by issue already created PR
 https://github.com/nmklotas/GitLabApiClient/pull/158

I can't merged this PR and make release

**Comment by TemoxaGreenMoney** [comment]
@nmklotas  check pls

**Comment by TemoxaGreenMoney** [comment]
![image](https://user-images.githubusercontent.com/42239650/92086078-e4390780-edf3-11ea-9013-a8bbd37774ee.png)

I am updated yesterday nuget package, but error not resolve

![image](https://user-images.githubusercontent.com/42239650/92086232-1a768700-edf4-11ea-9038-374d73da7180.png)
