### ISSUE TITLE
Can not get tags from GitLab

### ISSUE THREAD

**Issue by LightVolk** [nmklotas/GitLabApiClient#175]
Gitlab version: 13.3.1
GitLabApiClient version: 1.6.0.

I try to get all tags (and create some), but can not.
I write question on SO:  https://stackoverflow.com/questions/63885097/how-to-get-or-create-tags-at-gitlab

And i write simple code via RestSharp:

 ```
var client = new RestClient("https://gitlab.domain.local/");
 var request1 = new RestRequest("api/v4/projects/25/repository/tags?private_token=token_key", Method.GET);

```

So, i get response with all tags.

Response:

`[{"name":"test","message":"","target":"4ea68a3b316837bd3806257d8912f36ef4dd3b79","commit":{"id":"4ea68a3b316837bd3806257d8912f36ef4dd3b79","short_id":"4ea68a3b","created_at":"2020-09-14T10:45:43.000+03:00","parent_ids":[],"title":"add README","message":"add README\n","author_name":"User Name","author_email":"User.Name@gmail.com","authored_date":"2020-09-14T10:45:43.000+03:00","committer_name":"User Name","committer_email":"User.Name@gmail.com","committed_date":"2020-09-14T10:45:43.000+03:00","web_url":"https://gitlab.domain.local/user/tags-test-project/-/commit/4ea68a3b316837bd3806257d8912f36ef4dd3b79"},"release":{"tag_name":"test","description":"test release notes"},"protected":false}]`

And so on.
Can you tell me - is it bug or not?
And how to fix it?
Thank you!

**Comment by jetersen** [comment]
Without show what code you wrote when using this library I have no way of knowing what might have gone wrong.

```csharp
var client = new GitLabClient("https://gitlab.example.com", "your_private_token");
var tags = await client.Tags.GetAsync("group/project");
var tag = await client.Tags.CreateAsync("group/project", new CreateTagRequest(...))
```

**Comment by LightVolk** [comment]
This code works!
`var tag1s = await client.Tags.GetAsync(25);`

`var tags = await client.Tags.GetAsync("group/project");`  -  not works - i try 'usrname/tags-test-project'. I know, that it is not group, but how to know group name?

`var tag = await client.Tags.CreateAsync(25, new CreateTagRequest("autoTag", "master", "auto message", "auto release description"));`
This code works well too!

Thank you!

**Comment by jetersen** [comment]
`username/project` is not a valid path syntax according to gitlab api docs.

I suggest reading here: https://docs.gitlab.com/ee/user/group/
