### ISSUE TITLE
Trouble in Nuget? 

### ISSUE THREAD

**Issue by TemoxaGreenMoney** [nmklotas/GitLabApiClient#178]
I installed from nuget org this package
![image](https://user-images.githubusercontent.com/42239650/94778294-2e130e80-03ef-11eb-8001-9bd664ce64f1.png)

And get error from issue https://github.com/nmklotas/GitLabApiClient/issues/177

But if git clone this repository from branch master and add link to my project i am not get error! 

![image](https://user-images.githubusercontent.com/42239650/94778454-7cc0a880-03ef-11eb-9eff-cc157cb58c72.png)

**Comment by jetersen** [comment]
The build is not building properly on appveyor for some reason: https://ci.appveyor.com/project/nmklotas/gitlabapiclient

**Comment by TemoxaGreenMoney** [comment]
In nuget send version without last changes?

**Comment by jetersen** [comment]
Nuget packages are being sent from appveyor.

I created an issue with appveyor support: https://help.appveyor.com/discussions/problems/28307-build-not-running-whats-in-appveyoryml

**Comment by TemoxaGreenMoney** [comment]
@jetersen appveyor answered to you

**Comment by jetersen** [comment]
@nmklotas I do not have any permissions to the project on appveyor https://ci.appveyor.com/project/nmklotas/gitlabapiclient.

Perhaps we could move the NuGet package deployment to GitHub action.
Though you would need to add the API token to this repo under [settings/secrets](https://github.com/nmklotas/GitLabApiClient/settings/secrets). You can read more about it here: https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets

**Comment by TemoxaGreenMoney** [comment]
I dont have permissions to the Settings this repo, i think it can made one from contributers

**Comment by jetersen** [comment]
@TemoxaGreenMoney I was specifically mentioning @nmklotas the message for him 😄

**Comment by jparadnikas** [comment]
Hello, Sure I will do it now

**Comment by nmklotas** [comment]
@TemoxaGreenMoney Hello, I will update it now thanks!

**Comment by nmklotas** [comment]
@jetersen Hello, I have added NUGET_API_KEY to the secrets, thanks

**Comment by nmklotas** [comment]
I recommend to use github actions, they are so much better than AppVeyor :)

**Comment by jetersen** [comment]
I'll look into updating the github action workflow :)

**Comment by nmklotas** [comment]
nice 👍 i've added updated nuget api key to appveyor ;)

**Comment by jetersen** [comment]
Not sure it will help, seems appveyor is having trouble reading the appveyor.yml file 😓

**Comment by TemoxaGreenMoney** [comment]
@nmklotas  Hello!

But in nuget still has an old version
![image](https://user-images.githubusercontent.com/42239650/95038288-f27e8a00-06f7-11eb-8b0f-2504db55a7a3.png)

**Comment by jetersen** [comment]
#179 is not merged yet 👍

**Comment by jetersen** [comment]
realized that the latest nuget package was built without net48 because of project settings. Fixed in #182
