### ISSUE TITLE
Ability to use project name as id

### ISSUE THREAD

**Issue by Eibwen** [nmklotas/GitLabApiClient#18]
It seems the only way to limit things to a certain project is the int id.  And getting the int id is not easy on a large gitlab setup (took 2 minutes for me to `client.Projects.GetAsync()`)

The gitlab API does support escaped `group/project` endpoints.  I.e. `$"projects/{group}%2F{project}/repository/commits"`

I do not see a way to specify it in that fashion, but it would be very helpful

**Comment by casz** [comment]
I'd prefer projectId was just a string and was always encoded.

See https://github.com/gitlab4j/gitlab4j-api or https://github.com/jdalrymple/node-gitlab for good example of this

**Comment by casz** [comment]
released as [1.2.0](https://github.com/nmklotas/GitLabApiClient/releases/tag/1.2.0)
