### ISSUE TITLE
IssueId vs IssueIid in IssueUpdateRequest

### ISSUE THREAD

**Issue by splitt3r** [nmklotas/GitLabApiClient#19]
I think this https://github.com/nmklotas/GitLabApiClient/blob/6dbcd96da0d132afb8cfd5ae7e934a901f56d0e1/src/GitLabApiClient/Models/Issues/Requests/UpdateIssueRequest.cs#L19 should be the IssueIid. While using the lib i noticed a 404 error after passing the IssueId instead of the Iid here. Also the comment indicates that the Iid should be passed here.

Anyway great lib 👍

**Comment by nmklotas** [comment]
Thanks! I will look into it
