### ISSUE TITLE
Oauth Bearer Token Authorization

### ISSUE THREAD

**Issue by LeandroPT** [nmklotas/GitLabApiClient#21]
The authentitaion should be wider than the PRIVATE_TOKEN

With Oauth we should also be able to send a Bearer Token

https://docs.gitlab.com/ee/api/oauth2.html#access-gitlab-api-with-access-token

For what i can see the change is on private GitLabHttpFacade:

https://github.com/nmklotas/GitLabApiClient/blob/bef459a658c3a7d9a84ec6a0be66880cc23b4c2d/src/GitLabApiClient/Internal/Http/GitLabHttpFacade.cs#L12

in this moment:
https://github.com/nmklotas/GitLabApiClient/blob/bef459a658c3a7d9a84ec6a0be66880cc23b4c2d/src/GitLabApiClient/Internal/Http/GitLabHttpFacade.cs#L26

The request is made with the header Key **Authorization** and value: **Bearer {Token}**

**Comment by casz** [comment]
I added support for bearer token and even added support for requesting an API token with username and password.
