### ISSUE TITLE
ProjectMergeRequestsQueryOptions

### ISSUE THREAD

**Issue by mlinduska** [nmklotas/GitLabApiClient#22]
Hello, I'd like to report a following bug:

**What happened:**
Calling `MergeRequestsClient.GetAsync` method with `ProjectMergeRequestsQueryOptions` and specifying `MergeRequestsIds` does not filter it.

**Repro steps:**
Example code:
`client.MergeRequests.GetAsync(projectId, o => { o.State = GitLabApiClient.Models.MergeRequests.Requests.QueryMergeRequestState.Merged; o.MergeRequestsIds.Add(mergeRequestId); });`

Such call returns all merged requests for given project, not just the one specified in the options property.

**Desired output:**
Only merge request with given id is returned.

I have also looked into the code and I think I know where the problem lays:
The two query builders (generic & project) are incorrectly switched in `GetAsync` methods in `MergeRequestsClient.cs`

https://github.com/nmklotas/GitLabApiClient/blob/bef459a658c3a7d9a84ec6a0be66880cc23b4c2d/src/GitLabApiClient/MergeRequestsClient.cs#L63 this method is for generic options but uses `_projectMergeRequestsQueryBuilder`

https://github.com/nmklotas/GitLabApiClient/blob/bef459a658c3a7d9a84ec6a0be66880cc23b4c2d/src/GitLabApiClient/MergeRequestsClient.cs#L46 this method is for project options but uses generic `_mergeRequestsQueryBuilder`

**Comment by nmklotas** [comment]
Thanks for bringing this up!

**Comment by nmklotas** [comment]
Thanks, I've merged your fix into 1.0.3.
