### ISSUE TITLE
Support for creating a Release on a GitLab Project

### ISSUE THREAD

**Issue by gep13** [nmklotas/GitLabApiClient#24]
Is there currently support for this:

https://gitlab.com/help/user/project/releases/index

Thanks

**Comment by nmklotas** [comment]
Hi, unfortunately there's no support for that. I would be happy to accept PR for this :)

**Comment by gep13** [comment]
@nmklotas just getting started playing with GitLab and working against the REST API.  If I can up and running with it, I will try to send some code back into this repository.
