### ISSUE TITLE
Support Markdown API 

### ISSUE THREAD

**Issue by Starina123** [nmklotas/GitLabApiClient#31]
Hi.

Are you planning to add support for [Markdown API ](https://docs.gitlab.com/ee/api/markdown.html)?

**Comment by nmklotas** [comment]
Hi,

Yes it should be supported eventually, I'm happy to accept PR for this.

**Comment by dnagl** [comment]
The support for markdown is done with PR #45 

Have fun with it guys :)

**Comment by MurashovAlexander** [comment]
Hi!

How to create **MarkdownClient**?

Please, add property **MarkdownClient** in **GitLabClient.cs**

**Comment by dnagl** [comment]
@MurashovAlexander 
Thanks for your attention  - I forgot about this. I'll fix it asap (probably today or tomorrow)

**Comment by dnagl** [comment]
@nmklotas Thanks for reopening - I think I'll have to fix my previous commits as well ...

**Comment by MurashovAlexander** [comment]
404 not found exception, not working :confused:

**Comment by dnagl** [comment]
@MurashovAlexander Maybe you could try to build #47 and verify that it is now working?

**Comment by MurashovAlexander** [comment]
@dnagl yes, its working. 😄 

@nmklotas Please, merge with master branch.
