### ISSUE TITLE
Support Namespaced path encoding calls

### ISSUE THREAD

**Issue by Starina123** [nmklotas/GitLabApiClient#33]
GitLab API has two ways to access the project info (see [doc](https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding)).

1. By project ID (ex. https://gitlab.com/api/v4/projects/13083).
2. By namespace and project name (ex. https://gitlab.com/api/v4/projects/gitlab-org%2fgitlab-ce).

Add this functionality please.

**Comment by Starina123** [comment]
I looked the code. Now some methods use ```int projectId``` some ```string projectId```. See [IssuesClient.cs ](https://github.com/nmklotas/GitLabApiClient/blob/19456a7c7753c44787371f17d815071ed5e33965/src/GitLabApiClient/IssuesClient.cs#L52) for example and parametr description [hear](https://github.com/nmklotas/GitLabApiClient/blob/8dd8f51fd379e2ef000e4206b12d816f9ce11bac/src/GitLabApiClient/Models/Projects/Requests/CreateProjectLabelRequest.cs#L15).

If the ```projectId``` is encoded as URL (namespace and project name), then the replacement ```/``` to ```%2f``` should be in the library, otherwise users will have to do it all the time.

**Comment by casz** [comment]
Ya projectId should be string and was always encoded.

See https://github.com/gitlab4j/gitlab4j-api or https://github.com/jdalrymple/node-gitlab for good example of this

**Comment by casz** [comment]
released as [1.2.0](https://github.com/nmklotas/GitLabApiClient/releases/tag/1.2.0)
