### ISSUE TITLE
Add support for Pipelines

### ISSUE THREAD

**Issue by Stefan-J-Hanke** [nmklotas/GitLabApiClient#35]
I'd like to contribute pipelining support to this library, as mentioned in #25.
I think the basic functionality could be done like all other clients currently, as long as there is no other way forward.

Thoughts?

**Comment by nmklotas** [comment]
Hi,

Your PR would be very welcome. I agree that this should be done like in the other clients ;)
Not sure how this connects with #25? :/

**Comment by Stefan-J-Hanke** [comment]
Regading the other issue - it was just mentioned there, no real connection.

Glad you OK with that. Could take a week or so, currently I feel a bit load, but am determined to do it :)

**Comment by nmklotas** [comment]
Great. If you need something just ask!

**Comment by Stefan-J-Hanke** [comment]
The [Pipeline page](https://docs.gitlab.com/ce/api/pipelines.html) contain an example where there is a user. How do you think this should be implemented? Should I reuse `GitLabApiClient.Models.Users.Responses.User` or create a separate model class? I'd tend to latter since it looks like containing only a small subset of information.

There are two different representations of pipelines. When one lists pipelines, only 5 attributes are returned, whereas the result for a single pipeline contains much more. How would you like it to be implemented? I tend to create a `Pipeline` class for the 5 attributes and another `PipelineDetails` for the second one. This is different from e.g. the [merge requests](https://docs.gitlab.com/ce/api/merge_requests.html) where it looks like listing MRs contains the full information.

**Comment by WebDucer** [comment]
@Stefan-J-Hanke How far is you implementation? We need this for our project, so I plan to implement pipeline client during next one or two weeks. If there is no implementation at this moment, I will start from scratch.

**Comment by Stefan-J-Hanke** [comment]
@WebDucer please take it. I did not find the time to get the testing story working :-/. Unfortunately I cannot share the code, but this shouldn't be an issue; it's not that much.

**Comment by WebDucer** [comment]
@Stefan-J-Hanke Ok. I'm working on it. Get methods alredy implemented is in our internal testing. Write methods are on the way. I hope to be able to make a PR end of this week.

@nmklotas What is the best ability for unit testing? I see a `localhost` as server, that is used. It is only for your local tests or do you have some CI pipelene that can execute the commands (integration tests)?

**Comment by Stefan-J-Hanke** [comment]
@WebDucer  FWIW, the test uses `docker-compose` to fire up a local GitLab instance, sets default credentials via scripts and the test then waits for the instance to be up and running.

https://github.com/nmklotas/GitLabApiClient/blob/master/test/GitLabApiClient.Test/Utilities/GitLabContainerFixture.cs

**Comment by WebDucer** [comment]
@Stefan-J-Hanke Integration tests could be difficult with pipelines. This needs an agent (for execution) and a repo with `.gitlab-ci.yml` file as pipeline trigge 😞 

Any idea?

The implementation is finished and added as PR.

**Comment by casz** [comment]
#75 is now included in the nuget package
