### ISSUE TITLE
Use release drafter for GitHub releases

### ISSUE THREAD

**Issue by casz** [nmklotas/GitLabApiClient#48]
Release drafter uses Pull requests and labels to generate release notes :)

Read more about release drafter here: https://github.com/toolmantim/release-drafter

See usage here: https://github.com/jenkinsci/configuration-as-code-plugin/releases
See example config here: https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml

**Comment by casz** [comment]
Now with GitHub actions enabled this should be super easy to enable :smile

**Comment by casz** [comment]
Fixed in https://github.com/nmklotas/GitLabApiClient/commit/1f6d269b4564c1ba6806ac65ae90c9d1cd2eef12

**Comment by casz** [comment]
and in https://github.com/nmklotas/GitLabApiClient/commit/b274a82ab8422bb04758f030eaf66ac78c923466 we need some config :)

**Comment by casz** [comment]
Release drafter at work:
![image](https://user-images.githubusercontent.com/1661688/68798521-da70c880-0656-11ea-850a-bc4f716218b5.png)

**Comment by nmklotas** [comment]
Looks amazing :)
