### ISSUE TITLE
Is the development of supporting more API is in progress?

### ISSUE THREAD

**Issue by nicholasyin** [nmklotas/GitLabApiClient#54]
For example, the operations to branches?

**Comment by casz** [comment]
Feel free to contribute? :)

**Comment by nicholasyin** [comment]
Hahaha, lemme read the infrastructure first.

**Comment by casz** [comment]
@nicholasyin #61 should fix up the branch client :)

**Comment by nmklotas** [comment]
yes, it's in progress :)

**Comment by tellespallabob** [comment]
I was trying to push some features which are not supported right now, do I need you to grant permissions to be able to push to origin?
Specifically I was adding support to add/update/delete environment variables in a project.

**Comment by casz** [comment]
@tellespallabob you need to fork the repo and open a pull request from your branch

https://help.github.com/en/articles/fork-a-repo
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by casz** [comment]
I'll close this as it is a constant work in progress 😅
