### ISSUE TITLE
NuGet API key expired

### ISSUE THREAD

**Issue by casz** [nmklotas/GitLabApiClient#88]
@nmklotas Could you generate a new API key and add to appveyor.yml?

Error publishing package.\
NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.

**Comment by nmklotas** [comment]
Hello,

yees, I will do that asap

**Comment by casz** [comment]
Hope you don't mind the recent changes I did to publishing 😰

**Comment by nmklotas** [comment]
I trust you. I've changed the api key ;)

**Comment by casz** [comment]
Cheers 🥰
