### ISSUE TITLE
How to get project id?

### ISSUE THREAD

**Issue by gep13** [nmklotas/GitLabApiClient#94]
This could be a silly question, and I apologise in advance if this is covered elsewhere, but I can't immediately find a way to get what I need...

I want to be able to get all the Milestones for a project that I have on gitlab.com.  The project in question is https://gitlab.com/gep13/fakeproject.  In order to get the milestones, I have to provide the project id, and I don't see a way to get this information easily.  Can you please provide an example to explain what I am missing?

Thanks!

**Comment by casz** [comment]
simply use `gep13/fakeproject` or look here: 
![image](https://user-images.githubusercontent.com/1661688/70529931-0302ba00-1b52-11ea-88db-e62e02756372.png)

**Comment by gep13** [comment]
@casz perfect, thank you very much!
