### ISSUE TITLE
Issue when creating Release through API

### ISSUE THREAD

**Issue by gep13** [nmklotas/GitLabApiClient#96]
I have just attempted to create a GitLab Release through the API when the tag doesn't currently exist on the Repository.  When I did this, I got the following response in Fiddler:

![image](https://user-images.githubusercontent.com/1271146/70571388-b5a83c00-1b95-11ea-8af7-0086dffb3a69.png)

Looking at the documentation, it suggests that when the tag doesn't exist, I can specify a `Ref` to point to:

https://docs.gitlab.com/ee/api/releases/#create-a-release

![image](https://user-images.githubusercontent.com/1271146/70571453-d7092800-1b95-11ea-8602-07ac8618849c.png)

However, I don't see anywhere in the `CreateReleaseRequest` class that maps to the `Ref` parameter.

Does this exist somewhere?  Or is this something that needs to be added to the GitLabApiClient?

**Comment by casz** [comment]
I believe this is something that was not added to the API.

**Comment by gep13** [comment]
@casz I only started using this library yesterday, and I haven't started digging into the code yet.  Having the ability to set the `Ref` property is something that I would like to see added to the library.  Can you please give me some pointers on what code needs to be added, and I would be happy to submit a PR to get it added.  Thanks.

**Comment by casz** [comment]
https://github.com/nmklotas/GitLabApiClient/blob/master/src/GitLabApiClient/Models/Releases/Requests/CreateReleaseRequest.cs seems to only consider one use case so it will properly need to be modified
