### ISSUE TITLE
Get issues from Group of projects

### ISSUE THREAD

**Issue by yteruel31** [nmklotas/GitLabApiClient#97]
Add the ability to get all issues from Group.

Doc Gitlab API : 
https://docs.gitlab.com/ee/api/issues.html#list-group-issues

**Comment by WebDucer** [comment]
@casz @yteruel31 I will implement this during this week. We also need issues for all projects of a group. The same for the group labels (only labels of the group).

**Comment by WebDucer** [comment]
As I see, the `Issues` client uses `GetAsync` overloads to get issues (in general) and to get project issues. If we extend this for groups, the overloads are not unique:

```charp
public async Task<IList<Issue>> GetAsync(ProjectId projectId, Action<ProjectIssuesQueryOptions> options = null)

public async Task<IList<Issue>> GetAsync(GroupId projectId, Action<GroupIssuesQueryOptions> options = null)
```

`ProjectId` and `GroupId` are normaly implicitly converted from string (name) or id (int). I think, we have to mark the project `GetAsync` method as **DEPRECATED** and use more explizit method names, like:

- `GetForProjectAsync` or `GetProjectIssuesAsync`
- `GetForGroupAsync` or `GetGroupIssuesAsync`

The `IssuesQueryOptions` shoudl be than used for all three access possibilities.

An another possibility would be to move the project / group issue end point to the project / group client.

@casz @nmklotas How should we go here?

**Comment by casz** [comment]
I would like to reference how this was implemented in node-gitlab

https://github.com/node-gitlab/node-gitlab/blob/481876c186873e8264b6b3c18a8dfc6842658279/src/core/services/Issues.ts#L28-L32

Here you have to use named object map, we could achieve the same.

**Comment by casz** [comment]
In general I see several issues in our clients that I want to tackle to get a similar structure to node-gitlab.

**Comment by WebDucer** [comment]
So we wood have something like:

```csharp
GetAllAsync(ProjectId projectId = null, GroupId groupId = null, Action<IssueQueryOptions> options = null)
```

**Comment by casz** [comment]
That could definitely work @WebDucer

**Comment by WebDucer** [comment]
@casz OK. Then I mark the two `GetAync` mehtods as obsolet and create a new `GetAllAsync` in the issues client.
